name: Build Project

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1
      - name: Code style
        run: ./gradlew projectCodestyle
      - name: Assemble
        run: ./gradlew assemble
      - name: Jacoco test report
        run: ./gradlew projectCoverage
      - name: Codecov report upload
        run: bash <(curl -s https://codecov.io/bash) -t ${{ secrets.CODECOV_TOKEN }}
      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: /**/build/reports/tests
      - name: Upload jacoco report
        uses: actions/upload-artifact@v2
        with:
          name: jacoco-report
          path: /**/build/reports/jacoco

